version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "12:30"
    timezone: Asia/Chongqing
  open-pull-requests-limit: 99
  versioning-strategy: increase
