on:
  push:
    branches: [ main ]

jobs:
  build-then-upload:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        check-latest: true
    - run: npm install
    - run: node . > gfwlist_hosts.txt
    - run: ls -lh gfwlist_hosts.txt
    - uses: actions/upload-artifact@v2
      with:
        name: gfwlist_hosts
        path: gfwlist_hosts.txt

      env:
        CI: true
