on:
  push:
    branches: [ $default-branch ]

jobs:
  build-then-upload:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '*'
    - run: npm install
    - run: node . > gfwlist_hosts.txt
    - run: ls -lh gfwlist_hosts.txt
    - uses: actions/upload-artifact@v2
      with:
        path: gfwlist_hosts.txt

      env:
        CI: true
