on:
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: curl -sL https://deb.nodesource.com/setup_current.x | sudo -E bash -
    - run: sudo apt-get install -y nodejs
    - run: node -v && npm -v
    - run: npm install
    - run: node . > gfwlist_hosts.txt
    - run: ls -lh gfwlist_hosts.txt

      env:
        CI: true
